version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MEMORY: 2G
      TYPE: FORGE
      VERSION: 1.18.2
      FORGEVERSION: 40.1.30
      # Need to download Server-Files-0.4.13.zip and
      # put it in modpacks directory next to this compose file
      GENERIC_PACK: /modpacks/Server-Files-0.4.13.zip
    ports:
      - "25565:25565"
